### PR TITLE
Typescript rewrite

### LINKED ISSUE #75: Typescript support
Hello,

Thanks for creating a great library !!
I would like to use it with a Typescript project. Do you have any Type definition files which can be used?

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This rewrites the project to using typescript. Closes #75 

All tests pass. Coverage is missing 3 lines `32, 45 and 133`.

## Breaking changes:

Since most people use bundlers nowadays it should be safe enough to drop webpack, etc. as the build tools from the project the person is using this on should be responsible for bundling not the library. In saying this I'd be okay with adding the webpack build back if it's really wanted.

**NOTE: If you feel this is too big of a change feel free to close this.**

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Sorry for the extra commits I missed a few things on the first pass.

Also I know a few places have `any` or possibly incorrect types but this brings us a lot closer. I'll be happy to fix those issues as I have the time but I feel this should be merged first if possible.

**Comment by mithunsatheesh** [comment]
@OmgImAlexis Thanks for the contribution. Can you raise PR against 8.0.0 branch?
Once stable we can merge on mainline.

**Comment by OmgImAlexis** [comment]
> @OmgImAlexis Thanks for the contribution. Can you raise PR against 8.0.0 branch?
> 
> Once stable we can merge on mainline.
> 
> 
> 
> Also consider any documentation updates which might be needed.

Can do. I'll make sure everything is sorted tomorrow and then I'll ping you to take another look. 🙏

**Comment by OmgImAlexis** [comment]
@mithunsatheesh did you want to merge this PR and for me to open a new PR with the doc changes or keep adding commits here?

**Comment by mithunsatheesh** [comment]
@OmgImAlexis I meant let's merge the code in 8.0.0 release branch. Would need to look into integrations and readme files a bit to ensure its ready to merge in mainline.

**Comment by nsingh2510** [comment]
@mithunsatheesh @OmgImAlexis  When are we expecting to be released. Looking for TS support for node-rules. Any eta.

**Pull request merged**
